# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

addLabel:
  is_secure: true
  credentials: Admin

manageLabel:
  is_secure: true
  credentials: Admin

languageList:
  is_secure: true
  credentials: Admin

addLanguageGroup:
  is_secure: true
  credentials: Admin

editLanguageGroup:
  is_secure: true
  credentials: Admin
  
manageLabel:
  is_secure: true
  credentials: Admin
  
languageGroupList:
  is_secure: true
  credentials: Admin

generateDictionary:
  is_secure: true
  credentials: [[Admin, Moderator]]