<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('User', 'doctrine');

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $login_name
 * @property string $password
 * @property integer $user_type_id
 * @property Doctrine_Collection $UserType
 * 
 * @method integer             getUserId()       Returns the current record's "user_id" value
 * @method string              getLoginName()    Returns the current record's "login_name" value
 * @method string              getPassword()     Returns the current record's "password" value
 * @method integer             getUserTypeId()   Returns the current record's "user_type_id" value
 * @method Doctrine_Collection getUserType()     Returns the current record's "UserType" collection
 * @method User                setUserId()       Sets the current record's "user_id" value
 * @method User                setLoginName()    Sets the current record's "login_name" value
 * @method User                setPassword()     Sets the current record's "password" value
 * @method User                setUserTypeId()   Sets the current record's "user_type_id" value
 * @method User                setUserType()     Sets the current record's "UserType" collection
 * 
 * @package    localizit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_user');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('login_name', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('password', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('user_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserType', array(
             'local' => 'user_type_id',
             'foreign' => 'id'));
    }
}