<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Language', 'doctrine');

/**
 * BaseLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $language_id
 * @property string $language_code
 * @property string $language_name
 * @property string $language_status
 * @property Doctrine_Collection $LanguageLabelString
 * @property Doctrine_Collection $LanguageLabelString_4
 * @property Doctrine_Collection $UserLanguage
 * 
 * @method integer             getLanguageId()            Returns the current record's "language_id" value
 * @method string              getLanguageCode()          Returns the current record's "language_code" value
 * @method string              getLanguageName()          Returns the current record's "language_name" value
 * @method string              getLanguageStatus()        Returns the current record's "language_status" value
 * @method Doctrine_Collection getLanguageLabelString()   Returns the current record's "LanguageLabelString" collection
 * @method Doctrine_Collection getLanguageLabelString4()  Returns the current record's "LanguageLabelString_4" collection
 * @method Doctrine_Collection getUserLanguage()          Returns the current record's "UserLanguage" collection
 * @method Language            setLanguageId()            Sets the current record's "language_id" value
 * @method Language            setLanguageCode()          Sets the current record's "language_code" value
 * @method Language            setLanguageName()          Sets the current record's "language_name" value
 * @method Language            setLanguageStatus()        Sets the current record's "language_status" value
 * @method Language            setLanguageLabelString()   Sets the current record's "LanguageLabelString" collection
 * @method Language            setLanguageLabelString4()  Sets the current record's "LanguageLabelString_4" collection
 * @method Language            setUserLanguage()          Sets the current record's "UserLanguage" collection
 * 
 * @package    localizit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_language');
        $this->hasColumn('language_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('language_code', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('language_name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('language_status', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LanguageLabelString', array(
             'local' => 'language_id',
             'foreign' => 'language_id'));

        $this->hasMany('LanguageLabelString as LanguageLabelString_4', array(
             'local' => 'language_id',
             'foreign' => 'language_id'));

        $this->hasMany('UserLanguage', array(
             'local' => 'language_id',
             'foreign' => 'language_id'));
    }
}