<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserLanguage', 'doctrine');

/**
 * BaseUserLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $language_id
 * @property Doctrine_Collection $OhrmLanguage
 * @property Doctrine_Collection $OhrmUser
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getUserId()       Returns the current record's "user_id" value
 * @method integer             getLanguageId()   Returns the current record's "language_id" value
 * @method Doctrine_Collection getOhrmLanguage() Returns the current record's "OhrmLanguage" collection
 * @method Doctrine_Collection getOhrmUser()     Returns the current record's "OhrmUser" collection
 * @method UserLanguage        setId()           Sets the current record's "id" value
 * @method UserLanguage        setUserId()       Sets the current record's "user_id" value
 * @method UserLanguage        setLanguageId()   Sets the current record's "language_id" value
 * @method UserLanguage        setOhrmLanguage() Sets the current record's "OhrmLanguage" collection
 * @method UserLanguage        setOhrmUser()     Sets the current record's "OhrmUser" collection
 * 
 * @package    localizit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_user_language');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('language_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OhrmLanguage', array(
             'local' => 'language_id',
             'foreign' => 'language_id'));

        $this->hasMany('OhrmUser', array(
             'local' => 'user_id',
             'foreign' => 'user_id'));
    }
}