<?php

/**
 * BaseSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $value
 * @property integer $groupId
 * @property text $note
 * @property Group $Group
 * @property Doctrine_Collection $Target
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method text                getValue()   Returns the current record's "value" value
 * @method integer             getGroupId() Returns the current record's "groupId" value
 * @method text                getNote()    Returns the current record's "note" value
 * @method Group               getGroup()   Returns the current record's "Group" value
 * @method Doctrine_Collection getTarget()  Returns the current record's "Target" collection
 * @method Source              setId()      Sets the current record's "id" value
 * @method Source              setValue()   Sets the current record's "value" value
 * @method Source              setGroupId() Sets the current record's "groupId" value
 * @method Source              setNote()    Sets the current record's "note" value
 * @method Source              setGroup()   Sets the current record's "Group" value
 * @method Source              setTarget()  Sets the current record's "Target" collection
 * 
 * @package    localizit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_source');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('value', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('group_id as groupId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('note', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Group', array(
             'local' => 'groupId',
             'foreign' => 'id',
             'onDelete' => 'set null'));

        $this->hasMany('Target', array(
             'local' => 'id',
             'foreign' => 'sourceId'));
    }
}