<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LanguageGroup', 'doctrine');

/**
 * BaseLanguageGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $group_name
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method string        getGroupName()  Returns the current record's "group_name" value
 * @method LanguageGroup setId()         Sets the current record's "id" value
 * @method LanguageGroup setGroupName()  Sets the current record's "group_name" value
 * 
 * @package    localizit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLanguageGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_language_group');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('group_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}