<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $firstName
 * @property string $lastName
 * @property string $email
 * @property string $username
 * @property integer $userTypeId
 * @property string $password
 * @property UserType $UserType
 * @property Doctrine_Collection $UserLanguage
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getFirstName()    Returns the current record's "firstName" value
 * @method string              getLastName()     Returns the current record's "lastName" value
 * @method string              getEmail()        Returns the current record's "email" value
 * @method string              getUsername()     Returns the current record's "username" value
 * @method integer             getUserTypeId()   Returns the current record's "userTypeId" value
 * @method string              getPassword()     Returns the current record's "password" value
 * @method UserType            getUserType()     Returns the current record's "UserType" value
 * @method Doctrine_Collection getUserLanguage() Returns the current record's "UserLanguage" collection
 * @method User                setId()           Sets the current record's "id" value
 * @method User                setFirstName()    Sets the current record's "firstName" value
 * @method User                setLastName()     Sets the current record's "lastName" value
 * @method User                setEmail()        Sets the current record's "email" value
 * @method User                setUsername()     Sets the current record's "username" value
 * @method User                setUserTypeId()   Sets the current record's "userTypeId" value
 * @method User                setPassword()     Sets the current record's "password" value
 * @method User                setUserType()     Sets the current record's "UserType" value
 * @method User                setUserLanguage() Sets the current record's "UserLanguage" collection
 * 
 * @package    localizit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_user');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('firstName', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('lastName', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('email', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('username', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('user_type_id as userTypeId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserType', array(
             'local' => 'userTypeId',
             'foreign' => 'id'));

        $this->hasMany('UserLanguage', array(
             'local' => 'id',
             'foreign' => 'userId'));
    }
}