<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserType', 'doctrine');

/**
 * BaseUserType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $user_type
 * @property Doctrine_Collection $User
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getUserType()  Returns the current record's "user_type" value
 * @method Doctrine_Collection getUser()      Returns the current record's "User" collection
 * @method UserType            setId()        Sets the current record's "id" value
 * @method UserType            setUserType()  Sets the current record's "user_type" value
 * @method UserType            setUser()      Sets the current record's "User" collection
 * 
 * @package    localizit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_user_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_type', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'user_type_id'));
    }
}