<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Label', 'doctrine');

/**
 * BaseLabel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $label_id
 * @property string $label_name
 * @property string $label_comment
 * @property enum $label_status
 * @property Doctrine_Collection $LanguageLabelString
 * 
 * @method integer             getLabelId()             Returns the current record's "label_id" value
 * @method string              getLabelName()           Returns the current record's "label_name" value
 * @method string              getLabelComment()        Returns the current record's "label_comment" value
 * @method enum                getLabelStatus()         Returns the current record's "label_status" value
 * @method Doctrine_Collection getLanguageLabelString() Returns the current record's "LanguageLabelString" collection
 * @method Label               setLabelId()             Sets the current record's "label_id" value
 * @method Label               setLabelName()           Sets the current record's "label_name" value
 * @method Label               setLabelComment()        Sets the current record's "label_comment" value
 * @method Label               setLabelStatus()         Sets the current record's "label_status" value
 * @method Label               setLanguageLabelString() Sets the current record's "LanguageLabelString" collection
 * 
 * @package    localizit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLabel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_label');
        $this->hasColumn('label_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('label_name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('label_comment', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('label_status', 'enum', 1, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => '0',
              1 => '1',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LanguageLabelString', array(
             'local' => 'label_id',
             'foreign' => 'label_id'));
    }
}