<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmLanguageLabelString', 'doctrine');

/**
 * BaseOhrmLanguageLabelString
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $language_label_string_id
 * @property integer $label_id
 * @property integer $language_id
 * @property string $language_label_string
 * @property enum $language_label_string_status
 * @property OhrmLabel $OhrmLabel
 * @property OhrmLanguage $OhrmLanguage
 * 
 * @method integer                 getLanguageLabelStringId()        Returns the current record's "language_label_string_id" value
 * @method integer                 getLabelId()                      Returns the current record's "label_id" value
 * @method integer                 getLanguageId()                   Returns the current record's "language_id" value
 * @method string                  getLanguageLabelString()          Returns the current record's "language_label_string" value
 * @method enum                    getLanguageLabelStringStatus()    Returns the current record's "language_label_string_status" value
 * @method OhrmLabel               getOhrmLabel()                    Returns the current record's "OhrmLabel" value
 * @method OhrmLanguage            getOhrmLanguage()                 Returns the current record's "OhrmLanguage" value
 * @method OhrmLanguageLabelString setLanguageLabelStringId()        Sets the current record's "language_label_string_id" value
 * @method OhrmLanguageLabelString setLabelId()                      Sets the current record's "label_id" value
 * @method OhrmLanguageLabelString setLanguageId()                   Sets the current record's "language_id" value
 * @method OhrmLanguageLabelString setLanguageLabelString()          Sets the current record's "language_label_string" value
 * @method OhrmLanguageLabelString setLanguageLabelStringStatus()    Sets the current record's "language_label_string_status" value
 * @method OhrmLanguageLabelString setOhrmLabel()                    Sets the current record's "OhrmLabel" value
 * @method OhrmLanguageLabelString setOhrmLanguage()                 Sets the current record's "OhrmLanguage" value
 * 
 * @package    localizit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmLanguageLabelString extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_language_label_string');
        $this->hasColumn('language_label_string_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('label_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('language_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('language_label_string', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('language_label_string_status', 'enum', 1, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => '0',
              1 => '1',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmLabel', array(
             'local' => 'label_id',
             'foreign' => 'label_id'));

        $this->hasOne('OhrmLanguage', array(
             'local' => 'language_id',
             'foreign' => 'language_id'));
    }
}