<?php

/**
 * BaseUserType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $userType
 * @property Doctrine_Collection $User
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getUserType() Returns the current record's "userType" value
 * @method Doctrine_Collection getUser()     Returns the current record's "User" collection
 * @method UserType            setId()       Sets the current record's "id" value
 * @method UserType            setUserType() Sets the current record's "userType" value
 * @method UserType            setUser()     Sets the current record's "User" collection
 * 
 * @package    localizit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_user_type');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_type as userType', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'userTypeId'));
    }
}