<?php

/**
 * UserLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    localizit
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserLanguage extends BaseUserLanguage
{
     /**
     * Define Parameters
     * @var <type>
     */
    private $userManagementService;

    /**
     * Get the User Management service.And bind with DAO class.
     * @return <type>
     */
    private function getUserManagementService() {
        $this->userManagementService = new UserManagementService();
        $this->userManagementService->setUserManagementDao(new UserManagementDao);
        return $this->userManagementService;
    }

    /**
     * Constructor. Initialization Authentication Service.
     */
    public function __construct() {
        $this->userManagementService = $this->getUserManagementService();
        parent::__construct();
    }


    /**
     *  Save records to database.
     * @return <type>
     */
    public function saveLang() {

        try {
            $userManagementService = $this->getUserManagementService();

            $values = $this->getValues();

            $addUser = $userManagementService->addUserLang($values['login_name'], $values['password'], $values['user_type']);

            return true;
        } catch (Exception $exc) {
            return false;
        }
    }

}
