# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /add-label
  param: { module: localization, action: addLabel }

add_label:
  url:   /add-label
  param: { module: localization, action: addLabel }

language_list:
  url:   /language-list
  param: { module: localization, action: languageList }

language_label_data_set:
  url:   /language-label-data-set
  param: { module: localization, action: languageLabelDataSet }

language_label_data_set_edit:
  url:   /language-label-data-set-edit
  param: { module: localization, action: editLanguageLabelData }

sign_in:
  url: /sign-in
  param: { module: authentication, action: login }

logout:
  url: /logout
  param: { module: authentication, action: logout }

loginpage:
  url: /
  param: { module: authentication, action: index }

generate_dictionary:
  url: /generate-dictionary
  param: { module: localization, action: generateDictionary }

download_dictionary:
  url: /download-dictionary
  param: { module: localization, action: downloadDictionary }

userManagement:
  url: /user-management
  param: { module: userManagement, action: index }

add_user:
  url: /add-user
  param: { module: userManagement, action: addUser }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
