prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            9464acab14bbcff6e58b8ff5c9667e829c7549f5

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    # Delays creation of a cache key until after checking whether an action or partial is cacheable
    lazy_cache_key:         true        

    standard_helpers:       [Partial, Cache, Url, I18N]

    # Default user culture
    i18n:                   true
    default_culture:        en_US

  .actions:
    login_module:           authentication
    login_action:           login