Source:
  tableName: ohrm_source
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    value:
      type: text
      notnull: true
    group_id:
      name: group_id as groupId
      type: integer
    note:
      type: text
  relations:
    Group:
      onDelete: set null
      local: groupId
      foreign: id
      class: Group
      type: one
      foreignAlias: Source
      foreignType: many

Target:
  tableName: ohrm_target
  options:
    collate: utf8_unicode_ci
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    source_id:
      name: source_id as sourceId
      type: integer
      notnull: true
    language_id:
      name: language_id as languageId
      type: integer
      notnull: true
    value:
      type: text
    note:
      type: text
  relations:
    Source:
      onDelete: CASCADE
      local: sourceId
      foreign: id
      class: Source
      type: one
      foreignAlias: Target
      foreignType: many
    Language:
      local: languageId
      foreign: id
      class: Language
      type: one
      foreignAlias: Target
      foreignType: many

Group:
  tableName: ohrm_group
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)

Language: 
  tableName: ohrm_language
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)
    code:
      type: string(255)

User:
  tableName: ohrm_user
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    firstName:
      type: string(250)
      notnull: true
    lastName:
      type: string(250)
      notnull: true
    email:
      type: string(250)
      notnull: true
    username:
      type: string(25)
      notnull: true
      autoincrement: false
    user_type_id:
      name: user_type_id as userTypeId
      type: integer
      notnull: true
    password:
      type: string(255)
  relations:
    UserType:
      local: userTypeId
      foreign: id
      class: UserType
      type: one
      foreignAlias: User
      foreignType: many

UserType:
  tableName: ohrm_user_type
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    user_type:
      name: user_type as userType
      type: string(25)
      notnull: true

UserLanguage:
  tableName: ohrm_user_language
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    user_id:
      name: user_id as userId
      type: integer
      notnull: true
    language_id:
      name: language_id as languageId
      type: integer
      notnull: true
  relations:
    Language:
      onDelete: CASCADE
      local: languageId
      foreign: id
      class: Language
      type: one
      foreignAlias: UserLanguage
      foreignType: many
    User:
      onDelete: CASCADE
      local: userId
      foreign: id
      class: User
      type: one
      foreignAlias: UserLanguage
      foreignType: many