Label:
  connection: doctrine
  tableName: ohrm_label
  columns:
    label_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    label_name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    label_comment:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    label_status:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    LanguageLabelString:
      local: label_id
      foreign: label_id
      type: many
    OhrmLanguageLabelString_3:
      class: OhrmLanguageLabelString
      local: label_id
      foreign: label_id
      type: many
Language:
  connection: doctrine
  tableName: ohrm_language
  columns:
    language_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    language_code:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    language_name:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    language_status:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    LanguageLabelString:
      local: language_id
      foreign: language_id
      type: many
    LanguageLabelString_4:
      class: LanguageLabelString
      local: language_id
      foreign: language_id
      type: many
LanguageLabelString:
  connection: doctrine
  tableName: ohrm_language_label_string
  columns:
    language_label_string_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    label_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    language_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    language_label_string:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    language_label_string_status:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Label:
      local: label_id
      foreign: label_id
      type: one
    Language:
      local: language_id
      foreign: language_id
      type: one
    OhrmLabel_3:
      class: OhrmLabel
      local: label_id
      foreign: label_id
      type: one
    OhrmLanguage_4:
      class: OhrmLanguage
      local: language_id
      foreign: language_id
      type: one
UserType:
  connection: doctrine
  tableName: ohrm_user_type
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    user_type:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
User:
  connection: doctrine
  tableName: ohrm_user
  columns:
    user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    login_name:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    user_type_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    UserType:
      local: user_type_id
      foreign: id
      type: one
UserLanguage:
  connection: doctrine
  tableName: ohrm_user_language
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    language_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    User:
      local: user_id
      foreign: user_id
      type: one
    Language:
      local: language_id
      foreign: language_id
      type: one
LanguageGroup:
  connection: doctrine
  tableName: ohrm_language_group
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    group_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false   
  